development: 
  adapter: async
           
test:
  adapter: async
               
production:
  adapter: redis
  channel_prefix: kgchess_production
  password: <%= ENV['REDIS_PASSWORD'] %>
  url: redis://:{password}@redis-15352.c44.us-east-1-2.ec2.cloud.redislabs.com:15352
